config/routes.rb
JTopStats::Application.routes.draw do
  resources :clips do
    collection {get :chart}
    collection {get :classics}
  end

  resources :artists

  resources :rankings
  resources :jtops, :path => 'jtop' do
    collection {get :list}
  end

  root :to => "jtops#index"

end

app/models/artist.rb
class Artist

  include DataMapper::Resource

  property :id, Serial

  property :name, String

  has n, :clips

  def clip_count
    clips.count
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    params[:c] ||= 'name'

    @artists = params[:c] != 'clip_count' ? Artist.all(:order => sort_order) : Artist.all

    direction = (params[:d] == 'up' ? 1 : -1)
    @artists = @artists.sort_by { |a| direction * a.clip_count} if params[:c] == 'clip_count'
  end

  def show
    params[:c] ||= 'title'

    @artist = Artist.find(params[:id])
    @clips = @artist.clips(:order => sort_order)
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<% title 'Liste des artistes' %>

<section id="content">
<table class="data">
	<thead><tr>
		<th class="name-col"><%= sort_link 'Name', :name %></th>
		<th class="clip-col"><%= sort_link 'Clips', :clip_count %></th>
	</tr></thead>
	<tbody>
		<% @artists.each do |artist|  %>
		<tr class="<%= cycle('odd', 'even') %>">
			<td><%= link_to artist.name, artist_path(artist) %></td>
			<td><%= artist.clip_count %></td>
		</tr>
		<% end %>
	</tbody>
</table>
</section>

app/views/artists/show.html.erb
<% charts_js %>
<%= title "#{@artist.name}" %>

<section id="content">
<%= form_tag(chart_clips_path, :method => :get) do %>
<%= image_submit_tag 'chart.png', :class => 'chart' %>
	<table class="data">
		<thead><tr>
			<th class="checkbox-col"><%= check_box_tag 'select_all' %></th>
			<th class="name-col"><%= sort_link 'Name', :title %></th>
		</tr></thead>
		<tbody>
			<% @clips.each do |clip|  %>
			<tr class="<%= cycle('odd', 'even') %> <%= clip.gold? ? 'gold' : nil %>">
				<td><%= check_box_tag 'clip_ids[]', clip.id, false, :id => "clip_id_#{clip.id}", :class => 'select' %></td>
				<td><%= clip.title # link_to clip.title, clip_path(clip)
				 %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
<%= image_submit_tag 'chart.png', :class => 'chart' %>
<% end %>
</section>